### ISSUE TITLE
Implement REST service to serve static gene information

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server-worker#85]
**Is your feature request related to a problem? Please describe.**
In VarFish Server, the gene information is currently store in the postgres database. This makes it harder to update. We would like to see this information in a RocksDB database.

**Describe the solution you'd like**
Implement a REST service to serve the static gene information.

**Describe alternatives you've considered**
N/A

**Additional context**
- There already is some gene-related information available in the varfish-server-worker database.
- We would like to use HGNC gene IDs within VarFish.

**Comment by holtgrewe** [comment]
**Planning Steps**

- [ ] collect data currently available in VarFish server
- [ ] collect which data should be there in addition

**Implementation Steps**

- [ ] obtain data via [bollonaster branch](https://github.com/bihealth/varfish-db-downloader/tree/bollonaster) of [varfish-db-downloader](https://github.com/bihealth/varfish-db-downloader)
- [ ] add serde-based data structure for representing the data
- [ ] implement import into a "static gene info" RocksDB database
- [ ] implement REST API for serving this information

**Comment by holtgrewe** [comment]
**VarFish Server Data**

- ACMG incidental finding lists, different versions
- gnomAD and ExAC gene constraint information
- OMIM and HPO terms for gene (primary source should now be the HPO, though)
- ortholog information (MGI), should come from HGNC in the future, though
- gene ID cross-link information (already exists in varfish-server-worker)
- number of variant assessments (pathogenic, likely pathogenic, unknown significance) in clinvar (should come from clinvar, precomputed on startup)
- NCBI gene information and RIF
